-- Drop everything first
drop index if exists auteur_pk;

drop table if exists auteur cascade;

drop table if exists auteur_evenement cascade;

drop table if exists auteur_type_auteur cascade;

drop table if exists bibliothecaire cascade;

drop table if exists document cascade;

drop table if exists document_genre_document cascade;

drop table if exists editeur cascade;

drop table if exists emprunteur cascade;

drop table if exists emprunteur_document cascade;

drop table if exists evenement cascade;

drop table if exists evenement_bibliothecaire cascade;

drop table if exists format cascade;

drop table if exists genre_document cascade;

drop table if exists livre cascade;

drop table if exists media cascade;

drop table if exists type_auteur cascade;

drop table if exists utilisateur cascade;

-- auteur : colonnes du script 1 + lien_wikipedia du script originel
create table
    auteur (
        id integer generated by default as identity primary key,
        nom varchar(255),
        prenom varchar(255),
        nationalite varchar(255),
        date_naissance date,
        date_deces date,
        ville_naissance VARCHAR(250) null,
        lien_wikipedia varchar(200)
    );

create table
    type_auteur (
        id integer generated by default as identity primary key,
        label varchar(50)
    );

create table
    auteur_type_auteur (
        id_auteur integer not null references auteur (id) on delete restrict on update restrict,
        id_type_auteur integer not null references type_auteur (id) on delete restrict on update restrict,
        primary key (id_auteur, id_type_auteur)
    );

create table
    evenement (
        id integer generated by default as identity primary key,
        description varchar(1000),
        date_debut date,
        date_fin date,
        lieu varchar(150)
    );

create table
    auteur_evenement (
        id_evenement integer not null references evenement (id) on delete restrict on update restrict,
        id_auteur integer not null references auteur (id) on delete restrict on update restrict,
        primary key (id_evenement, id_auteur)
    );

create table
    utilisateur (
        id integer generated by default as identity primary key,
        login varchar(25),
        mot_de_passe varchar(4000),
        nom varchar(60),
        prenom varchar(60)
    );

create table
    bibliothecaire (
        id_utilisateur integer not null references utilisateur (id) on delete restrict on update restrict,
        id integer generated by default as identity,
        login varchar(25),
        mot_de_passe varchar(4000),
        nom varchar(60),
        prenom varchar(60),
        primary key (id_utilisateur, id)
    );

create table
    emprunteur (
        id_utilisateur integer not null references utilisateur (id) on delete restrict on update restrict,
        id integer generated by default as identity,
        login varchar(25),
        mot_de_passe varchar(4000),
        nom varchar(60),
        prenom varchar(60),
        adresse varchar(200),
        email varchar(150),
        date_naissance date,
        date_fin_abonnement date,
        numero_carte char(10),
        primary key (id_utilisateur, id)
    );

create table
    editeur (
        id integer generated by default as identity primary key,
        nom_societe varchar(60),
        adresse varchar(200),
        lien_site_web varchar(200),
        lien_wikipedia varchar(200)
    );

create table
    format (
        id integer generated by default as identity primary key,
        longueur decimal,
        largeur decimal,
        poids decimal
    );

create table
    genre_document (
        id integer generated by default as identity primary key,
        nom varchar(60)
    );

create table
    document (
        id integer generated by default as identity primary key,
        id_auteur integer not null references auteur (id) on delete restrict on update restrict,
        id_format integer not null references format (id) on delete restrict on update restrict,
        id_editeur integer not null references editeur (id) on delete restrict on update restrict,
        lien_gif varchar(250),
        description varchar(1000),
        date_acquisition date,
        code_emplacement varchar(10),
        code_isbn char(13),
        code_emprunt varchar(20),
        specificite varchar(20),
        titre varchar(250),
        date_publication date,
        date_creation date,
        date_maj date
    );

create table
    document_genre_document (
        id_genre_document integer not null references genre_document (id) on delete restrict on update restrict,
        id_document integer not null references document (id) on delete restrict on update restrict,
        primary key (id_genre_document, id_document)
    );

-- livre : colonnes du script 1 + champs du script originel, hérite de document
create table
    livre (
        id integer generated by default as identity primary key,
        id_document integer not null references document (id) on delete restrict on update restrict,
        titre varchar(250),
        nb_pages integer,
        editeur varchar(250),
        date_publication date,
        created_at timestamp,
        updated_at timestamp,
        auteur_id integer references auteur (id)
    );

create table
    media (
        id_document integer not null references document (id) on delete restrict on update restrict,
        id integer generated by default as identity,
        id_auteur integer references auteur (id),
        id_format integer references format (id),
        id_editeur integer references editeur (id),
        lien_gif varchar(250),
        description varchar(1000),
        date_acquisition date,
        code_emplacement varchar(10),
        code_isbn char(13),
        code_emprunt varchar(20),
        specificite varchar(20),
        titre varchar(250),
        date_publication date,
        date_creation date,
        date_maj date,
        duree decimal,
        primary key (id_document, id)
    );

create table
    emprunteur_document (
        id_utilisateur integer not null,
        id_emprunteur integer not null,
        id_document integer not null references document (id) on delete restrict on update restrict,
        fin_emprunt date,
        prolongation boolean,
        fin_prolongation date,
        debut_emprunt date,
        primary key (id_utilisateur, id_emprunteur, id_document),
        foreign key (id_utilisateur, id_emprunteur) references emprunteur (id_utilisateur, id) on delete restrict on update restrict
    );

create table
    evenement_bibliothecaire (
        id_utilisateur integer not null,
        id_bibliothecaire integer not null,
        id_evenement integer not null references evenement (id) on delete restrict on update restrict,
        primary key (id_utilisateur, id_bibliothecaire, id_evenement),
        foreign key (id_utilisateur, id_bibliothecaire) references bibliothecaire (id_utilisateur, id) on delete restrict on update restrict
    );