-- ============================================================
--  Schéma bibliothèque
--  Basé sur crebas.sql, réécrit dans le style "propre" :
--    - tout en minuscules / snake_case (pas de IDDOCUMENT, etc.)
--    - clé primaire = id  (INTEGER GENERATED BY DEFAULT AS IDENTITY)
--    - clés étrangères = <table>_id  +  CONTRAINTE fk_... explicite
--    - dates de suivi en created_at / updated_at (TIMESTAMP)
-- ============================================================

-- Suppression (ordre inverse des dépendances) pour pouvoir rejouer le script
DROP TABLE IF EXISTS emprunt CASCADE;
DROP TABLE IF EXISTS document_genre_document CASCADE;
DROP TABLE IF EXISTS document CASCADE;
DROP TABLE IF EXISTS auteur_type_auteur CASCADE;
DROP TABLE IF EXISTS utilisateur CASCADE;
DROP TABLE IF EXISTS role_utilisateur CASCADE;
DROP TABLE IF EXISTS genre_document CASCADE;
DROP TABLE IF EXISTS format CASCADE;
DROP TABLE IF EXISTS editeur CASCADE;
DROP TABLE IF EXISTS type_auteur CASCADE;
DROP TABLE IF EXISTS auteur CASCADE;
DROP TABLE IF EXISTS type_document CASCADE;
DROP TABLE IF EXISTS bibliotheque CASCADE;


-- ------------------------------------------------------------
--  Tables de base (sans dépendances)
-- ------------------------------------------------------------

CREATE TABLE auteur (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom             VARCHAR(60) NOT NULL,
    prenom          VARCHAR(100) NOT NULL,
    nationalite     VARCHAR(255),
    date_naissance  DATE,
    date_deces      DATE,
    ville_naissance VARCHAR(250),
    lien_wikipedia  VARCHAR(200)
);

CREATE TABLE type_auteur (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label  VARCHAR(50) NOT NULL
);

CREATE TABLE editeur (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom            VARCHAR(100) NOT NULL,
    adresse        VARCHAR(200),
    lien_site_web  VARCHAR(200),
    lien_wikipedia VARCHAR(200)
);

CREATE TABLE format (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    longueur  DECIMAL,
    largeur   DECIMAL,
    poids     DECIMAL
);

CREATE TABLE genre_document (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(100) NOT NULL
);

CREATE TABLE role_utilisateur (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle  VARCHAR(100) NOT NULL
);

CREATE TABLE type_document (
   id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nom    VARCHAR(125)         NOT NULL
);
create table bibliotheque (
   id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nom     VARCHAR(250)         NOT NULL,
   adresse VARCHAR(350)         null,
   horaire_ouverture    TIME                 null,
   horaire_fermeture    TIME                 null
);

-- ------------------------------------------------------------
--  Tables avec dépendances (clés étrangères)
-- ------------------------------------------------------------

-- DOCUMENT -> auteur, format, editeur
CREATE TABLE document (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre            VARCHAR(250) NOT NULL,
    description      VARCHAR(1000),
    lien_gif         VARCHAR(250),
    code_emplacement VARCHAR(10),
    code_isbn        CHAR(13),
    code_emprunt     VARCHAR(20),
    specificite      VARCHAR(20),
    date_acquisition DATE,
    date_publication DATE,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP,
    auteur_id        INTEGER NOT NULL,
    format_id        INTEGER NOT NULL,
    editeur_id       INTEGER NOT NULL,
    type_id          INTEGER NOT NULL,
    bibliotheque_id      INTEGER NOT NULL,
    CONSTRAINT fk_document_auteur  FOREIGN KEY (auteur_id)  REFERENCES auteur(id),
    CONSTRAINT fk_document_format  FOREIGN KEY (format_id)  REFERENCES format(id),
    CONSTRAINT fk_document_editeur FOREIGN KEY (editeur_id) REFERENCES editeur(id),
    CONSTRAINT fk_document_bibliotheque FOREIGN KEY (bibliotheque_id) REFERENCES bibliotheque(id),
    CONSTRAINT fk_document_type    FOREIGN KEY (type_id)  REFERENCES type_document(id)
);

-- UTILISATEUR -> role_utilisateur
CREATE TABLE utilisateur (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login               VARCHAR(25) NOT NULL,
    mot_de_passe        VARCHAR(4000) NOT NULL,
    prenom              VARCHAR(60) NOT NULL,
    nom                 VARCHAR(60) NOT NULL,
    adresse             VARCHAR(200),
    email               VARCHAR(150) NOT NULL,
    date_naissance      DATE,
    date_fin_abonnement DATE,
    numero_carte        CHAR(10),
    max_emprunts        INTEGER NOT NULL,
    duree_emprunt_semaines INTEGER NOT NULL,
    role_utilisateur_id INTEGER NOT NULL,
    CONSTRAINT fk_utilisateur_role FOREIGN KEY (role_utilisateur_id) REFERENCES role_utilisateur(id)
);


-- ------------------------------------------------------------
--  Tables de liaison (relations N-N et emprunt)
-- ------------------------------------------------------------

-- AUTEUR <-> TYPE_AUTEUR  (un auteur peut avoir plusieurs types)
CREATE TABLE auteur_type_auteur (
    auteur_id      INTEGER NOT NULL,
    type_auteur_id INTEGER NOT NULL,
    PRIMARY KEY (auteur_id, type_auteur_id),
    CONSTRAINT fk_auteur_type_auteur_auteur FOREIGN KEY (auteur_id)      REFERENCES auteur(id),
    CONSTRAINT fk_auteur_type_auteur_type   FOREIGN KEY (type_auteur_id) REFERENCES type_auteur(id)
);

-- DOCUMENT <-> GENRE_DOCUMENT  (un document peut avoir plusieurs genres)
CREATE TABLE document_genre_document (
    document_id       INTEGER NOT NULL,
    genre_document_id INTEGER NOT NULL,
    PRIMARY KEY (document_id, genre_document_id),
    CONSTRAINT fk_doc_genre_document FOREIGN KEY (document_id)       REFERENCES document(id),
    CONSTRAINT fk_doc_genre_genre    FOREIGN KEY (genre_document_id) REFERENCES genre_document(id)
);

-- EMPRUNT : un utilisateur emprunte un document (avec attributs)
CREATE TABLE emprunt (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id   INTEGER NOT NULL,
    document_id      INTEGER NOT NULL,
    debut_emprunt       DATE NOT NULL,
    date_fin_prevue  DATE NOT NULL,
    date_rendu       DATE,
    prolongation BOOLEAN,
    
    CONSTRAINT fk_emprunt_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id),
    CONSTRAINT fk_emprunt_document    FOREIGN KEY (document_id)    REFERENCES document(id)
);